app/frontend/vesseg/main/forms.py
from flask_wtf import FlaskForm
from flask_login import current_user
from wtforms import StringField, SubmitField, SelectField, MultipleFileField, BooleanField
from wtforms.validators import ValidationError, DataRequired
from ..models import Project, Image, Mask, PredictionModel


class ProjectForm(FlaskForm):

    project = StringField('project', validators=[DataRequired()])
    submit = SubmitField('create')

    def validate_project(self, project):
        existing_project = Project.query.filter_by(user_id=current_user.id)\
            .filter_by(project=project.data).first()
        if existing_project is not None:
            raise ValidationError('please use a different project name.')


class UploadForm(FlaskForm):

    project_id = SelectField('select project for which to upload files', validators=[DataRequired()], coerce=int)
    files = MultipleFileField('choose directory of files')
    submit = SubmitField('upload')


class PreprocessForm(FlaskForm):

    project_id = SelectField('select project for preprocessing', validators=[DataRequired()], coerce=int)
    preprocess = SelectField('select preprocess routine', validators=[DataRequired()], coerce=int)
    submit = SubmitField('preprocess')

    def validate_project_id(self, project_id):
        image_data = Image.query.filter_by(project_id=project_id.data).first()
        if image_data is None:
            raise ValidationError('selected project does not contain image data. please first upload images.')


class PredictForm(FlaskForm):

    project_id = SelectField('select project for prediction', validators=[DataRequired()], coerce=int)
    predictionmodel_id = SelectField('select prediction model', validators=[DataRequired()], coerce=int)
    submit = SubmitField('predict')


class EvaluationForm(FlaskForm):

    project_id = SelectField('select project for evaluation', validators=[DataRequired()], coerce=int)
    predictionmodel_id = SelectField('select prediction model', validators=[DataRequired()], coerce=int)
    submit = SubmitField('evaluate')


class PredictionModelForm(FlaskForm):

    name = StringField('model name', validators=[DataRequired()])
    container = StringField('container name', validators=[DataRequired()])
    model_path = StringField('path to model, relative to .../data/models', validators=[DataRequired()])
    additional_arguments = StringField('addtl arguments separated by a space')
    submit = SubmitField('add model')

    def validate_name(self, name):
        existing_name = PredictionModel.query.filter_by(name=name.data).first()
        if existing_name is not None:
            raise ValidationError('model exists, please use a different model name.')

app/frontend/vesseg/main/__init__.py
from flask import Blueprint, redirect, url_for, request
from flask_login import current_user

bp = Blueprint('main', __name__, template_folder='templates', static_folder='static')

@bp.before_request
def restrict_to_users():
    if not current_user.is_authenticated:
        if request.path.startswith('/download'):
            pass 
        else:
            return redirect(url_for('auth.login'))

from . import routes

app/frontend/vesseg/main/routes.py
import os
import csv
from os.path import join
from pathlib import Path
import shutil
import datetime
import json
import click
from io import BytesIO
import requests
import zipfile
from functools import wraps
from flask import render_template, request, flash, redirect, url_for, current_app, send_file, jsonify, send_from_directory
from flask_login import current_user
from vesseg import db
from vesseg.main import bp
from vesseg.main.forms import ProjectForm, UploadForm, PreprocessForm, PredictForm, EvaluationForm, PredictionModelForm
from vesseg.models import Project, Image, PredictionModel, Mask, Task, User


# helper functions

def get_project_path(project_id):
    return Path(current_app.config['DATA_PATH'], 'projects', str(project_id))

def get_models_path():
    return Path(current_app.config['DATA_PATH'], 'models')

def get_data_path():
    return Path(current_app.config['DATA_PATH'])

def get_analysis_path(project_id):
    return Path(current_app.config['DATA_PATH'], 'projects', str(project_id), 'analysis')

def get_masks_path(project_id, predictionmodel_id):
    pm = PredictionModel.query.get(predictionmodel_id)
    pm_name = pm.name
    return Path(current_app.config['DATA_PATH'], 'projects', str(project_id), 'predicted', 'masks')


@bp.route('/')
def home():
    return render_template('main/home.html')


@bp.route('/project', methods=['GET', 'POST'])
def project():
    form = ProjectForm()
    if request.method == 'POST':
        if form.validate_on_submit():

            # Create project
            new_project = Project(project=form.project.data, user_id=current_user.id)
            db.session.add(new_project)
            db.session.commit()
            flash('project has been added')

            # Create folder structure for project on disk
            p_id = Project.query.filter_by(project=form.project.data, user_id=current_user.id).first().id
            folders = ['raw', 'preprocessed', 'predicted']
            [Path(get_project_path(p_id), f).mkdir(parents=True, exist_ok=True) for f in folders]

    projects = Project.query.filter_by(user_id=current_user.id).all()
    return render_template('main/project.html', form=form, projects=projects)


@bp.route('/project/delete', methods=['GET'])
def project_delete():
    p_id = request.args.get('project_id')

    # Remove folders and contents on disk
    remove_path = get_project_path(p_id)
    if remove_path.exists():
        shutil.rmtree(remove_path)

    # Remove database entries
    project = Project.query.filter_by(id=p_id).first()
    db.session.delete(project)
    db.session.commit()

    flash('project has been deleted')
    return redirect(url_for('main.project'))


@bp.route('/data', methods=['GET', 'POST'])
def data():
    form = UploadForm()
    form.project_id.choices = [(p.id, p.project) for p in Project.query.filter_by(user_id=current_user.id).all()]
    if request.method == 'POST':
        bio_img_formats = ['.vsi', '.ets'] 
        pil_img_formats = ['.png', '.jpg', '.jpeg', '.tif', '.tiff']     
        project_id = int(request.form['project_id'])
        file_path = request.form.get('file_path')
        file_path = request.files['file'].filename if file_path == 'undefined' else file_path
        file_parent = str(Path(file_path).parent).replace('.', '_').replace(' ', '_')
        file_stem = str(Path(file_path).stem).replace('.', '_').replace(' ', '_')
        file_suffix = str(Path(file_path).suffix)
        file_path = os.path.join(file_parent, file_stem + file_suffix)

        # Save file on disk
        if file_suffix not in bio_img_formats+pil_img_formats:
            return "File format not supported", 400
        elif file_suffix in bio_img_formats:
            cat = 'bio'
        elif file_suffix in pil_img_formats:
            cat = 'pil'
        
        save_path = os.path.join(get_project_path(project_id), 'raw', cat, file_path)
        Path(save_path).parent.mkdir(exist_ok=True, parents=True)
        for f in request.files.getlist('file'):
            f.save(save_path)

        # Create database entry
        if not file_suffix == '.ets':
            if not Image.query.filter_by(project_id=project_id, image=file_stem).all():
                new_image = Image(project_id=project_id, image=file_stem, upload_file_type=file_suffix)
                db.session.add(new_image)
                db.session.commit()
        
    return render_template('main/data.html', form=form)


def walk_directory_to_list(input_directory, val_fxn=lambda x: True):
    """Walks input directory to file list for bioformats reader. Takes a filepath validation function.
    """
    filelist = []

    if not os.path.isdir(input_directory):
        return filelist

    for root, dirs, files in os.walk(input_directory):
        for file in files:
            filepath = os.path.join(root, file)
            if val_fxn(filepath):
                filelist.append(filepath)
    return filelist


@bp.route('/predict', methods=['GET', 'POST'])
def predict():
    form = PredictForm()
    form.project_id.choices = [(p.id, p.project) for p in Project.query.filter_by(user_id=current_user.id).all()]
    form.predictionmodel_id.choices = [(m.id, m.name) for m in PredictionModel.query.filter_by().all()]
    if request.method == 'POST':
        if form.validate_on_submit():

            project_id = form.project_id.data
            tasks = []
            project_path = str(get_project_path(project_id))

            bio_img_formats = ['.vsi', '.ets'] 
            pil_img_formats = ['.png', '.jpg', '.jpeg', '.tif', '.tiff']     

            # Convert bio2png and pil2png 
            bio_path = Path(project_path, 'raw', 'bio')
            bio_files = walk_directory_to_list(bio_path, lambda x: Path(x).suffix in bio_img_formats)
            pil_path = Path(project_path, 'raw', 'pil')
            pil_files = walk_directory_to_list(pil_path, lambda x: Path(x).suffix in pil_img_formats)

            if not bio_files and not pil_files: 
                flash('No valid images added to project. Add images to project by going to the data section.', 'predict')
                return render_template('main/predict.html', form=form)
            if bio_files:
                tasks.append(('file_type_converter:latest', project_path, ['-i', '/data/raw/bio', '-o', '/data/preprocessed']))
            if pil_files:
                tasks.append(('processor:latest', project_path, ['-f', 'pil_to_png', '-i', '/data/raw/pil', '-o', '/data/preprocessed']))

            # Convert mode to plain RGB
            tasks.append(('processor:latest', project_path, ['-f', 'convert_mode', '-i', '/data/preprocessed', '-o', '/data/preprocessed']))

            # Resize to (512,512)
            tasks.append(('processor:latest', project_path, ['-f', 'resize', '-i', '/data/preprocessed', '-o', '/data/preprocessed']))

            # # Predict
            predictionmodel_id = form.predictionmodel_id.data
            pm = PredictionModel.query.get(predictionmodel_id)
            name = pm.name.replace(' ', '_').replace('.','_')
            container = pm.container
            data_path = str(get_data_path())
            model_path = os.path.join('/data/models', pm.model_path)
            prepro_path = os.path.join('/data/projects', str(project_id), 'preprocessed')
            pred_mask_path = os.path.join('/data/projects', str(project_id), 'predicted', name, 'masks')
            pred_olay_path = os.path.join('/data/projects', str(project_id), 'predicted', name, 'olays')
            additional_arguments = pm.additional_arguments.strip().split(' ') if pm.additional_arguments else []
            additional_arguments = [str(ag) for ag in additional_arguments]


            Path(project_path, 'predicted', name, 'masks').mkdir(parents=True, exist_ok=True)
            tasks.append((container, data_path, ['-i', prepro_path, '-o', pred_mask_path, '-m', model_path] + additional_arguments))

            # Add post-processing
            tasks.append(('processor:latest', project_path, ['-f', 'create_overlay', '-i', '/data/preprocessed', '-o', '/data/predicted/' + name + '/olays' ]))

            # Add analysis
            kwarg_str = '{"predictionmodel_name": "' + name +'"}'
            tasks.append(('processor:latest', project_path, ['-f', 'analyzer', '-i', '/data', '-o', '', '-k', kwarg_str]))
            
            # Add tasks
            task_ids = add_tasks(tasks, current_user.id, project_id)
            flash('Prediction tasks have been added to queue.', 'predict')
            task_ids = [{'task_id': task_id} for task_id in task_ids]
            return render_template('main/predict.html', form=form, tasks=task_ids)
    return render_template('main/predict.html', form=form)


@bp.route('/evaluate', methods=['GET', 'POST'])
def evaluate():
    form = EvaluationForm()
    form.project_id.choices = [(p.id, p.project) for p in Project.query.filter_by(user_id=current_user.id).all()]
    form.predictionmodel_id.choices = [(m.id, m.name) for m in PredictionModel.query.filter_by().all()]
    if request.method == 'POST':
        if form.validate_on_submit():
            project_id = form.project_id.data
            project_name = Project.query.get(project_id).project
            predictionmodel_id = form.predictionmodel_id.data
            predictionmodel_name = PredictionModel.query.get(predictionmodel_id).name

            # Update database and make evaluation list

            masks = walk_directory_to_list(join(get_project_path(project_id), 'predicted', predictionmodel_name, 'masks'), lambda x: x.endswith('.png'))

            if not masks:
                flash('No predictions found for the selected project model combination.')
                return redirect(url_for('main.evaluate'))

            evaluation = []

            for m in masks:
                mask_name = str(Path(m).stem)
                project_id = int(project_id)
                predictionmodel_id = int(predictionmodel_id)

app/frontend/vesseg/templates/main/admin.html
{% extends 'main/base.html' %}

{% block maincontent %}


    <div class="display-3">{% block title %}admin{% endblock title %}</div>
    <br>
    <ul>
        <li><a href="{{ url_for('main.admin_projects')}}">projects</a></li>
        <li><a href="{{ url_for('main.admin_models')}}">models</a></li>
    </ul>
    <br>


{% endblock maincontent %}
{% block script %}
{% endblock script %}

app/frontend/vesseg/templates/main/admin_models.html
{% extends 'main/base.html' %}

{% block maincontent %}

    <div class="display-4">{% block title %}model admin{% endblock title %}</div>

    <br>
    <hr>

    <form action="" method="post" role="form">
        {{ form.csrf_token }}
        <p>
            {{ form.name.label }} {{ form.name(size=10, class_='form-control') }}
        </p>
        <p>
            {{ form.container.label }} {{ form.container(size=10, class_='form-control') }}
        </p>
        <p>
            {{ form.model_path.label }} {{ form.model_path(size=10, class_='form-control') }}
        </p>
        <p>
            {{ form.additional_arguments.label }} {{ form.additional_arguments(size=10, class_='form-control') }}
        </p>
        {{ form.submit( class_='btn btn-outline-secondary') }}
    </form>   
    


    {% if form.name.errors %}
    <br>
    <br>
        {% for error in form.name.errors %}
            <div class="alert alert-danger" role="alert">
                {{ error }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endfor %}
    <br>
    <br>
    {% endif %}

    <br>
    <hr>
    
    <br>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">model</th>
                <th scope="col">container</th>
                <th scope="col">path</th>
                <th scope="col">additional arguments</th>
                <th scope="col">delete</th>
            </tr>
        </thead>
        <tbody>
        {% for p in pms %}
            <tr>
                <th scope="row"> {{ loop.index }}</th>
                <td>{{ p.name }}</td>
                <td>{{ p.container }}</td>
                <td>{{ p.model_path }}</td>
                <td>{{ p.additional_arguments }}</td>
                <td><a href="{{url_for('main.admin_models_delete', pm_id=p.id)}}">delete</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>



{% endblock maincontent %}
{% block script %}
{% endblock script %}

app/frontend/vesseg/templates/main/admin_projects.html
{% extends 'main/base.html' %}

{% block maincontent %}


    <div class="display-4">{% block title %}project admin{% endblock title %}</div>
    <br>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">project</th>
                <th scope="col">user</th>
                <th scope="col">created</th>
                <th scope="col">delete</th>
            </tr>
        </thead>
        <tbody>
        {% for p in projects %}
            <tr>
                <th scope="row"> {{ loop.index }}</th>
                <td>{{ p.Project.project }}</td>
                <td>{{ p.User.username}}</td>
                <td>{{ p.Project.created_on.strftime('%Y-%m-%d') }}</td>
                <td><a href="{{ url_for('main.admin_projects_delete', project_id=p.Project.id) }}">delete</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>



{% endblock maincontent %}
{% block script %}
{% endblock script %}

app/frontend/vesseg/templates/main/base.html
{% extends 'base.html' %}

{% block title %}{% endblock title %}

{% block content %}

    {% include 'navigation.html' %}

    <div class="container h-100">
        <div class="row justify-content-center h-100">
            <div class="col-8">

                {% block maincontent %}{% endblock maincontent %}


            </div>
        </div>
    </div>



{% endblock content %}

{% block script %}
{% endblock script %}

app/frontend/vesseg/templates/main/data.html
{% extends 'main/base.html' %}

{% block maincontent %}

    <div class="display-3">{% block title %}data{% endblock title %}</div>
    <br>
    <p>First, select project from drop-down for which you want to add data. Then, drag-and-drop the folder into the file dropzone. (To upload an entire folder, use drag-and-drop not the file-picker pop-up.)</p>
    <br>

    {{ form.project_id.label(class_='sr-only')}}
    {{ form.project_id(class_='custom-select') }}

    <br><br>

    <script>
        Dropzone.options.myDropzone = {
          headers: {'X-CSRF-TOKEN': "{{ csrf_token() }}"},
          paramName: "file",
          init: function() {
                this.on("sending", function(file, xhr, formData) {
                    formData.append("file_path", file.fullPath);
                    formData.append("project_id", document.getElementById("project_id").options[document.getElementById("project_id").selectedIndex].value);
                });
            }
        }
    </script>

    <form action="{{ url_for('main.data') }}" class="dropzone" id="my-dropzone">
    </form>

{% endblock %}


{% block script %}
{% endblock %}

app/frontend/vesseg/templates/main/evaluate.html
{% extends 'base.html' %}

{% block content %}

    {% include 'navigation.html' %}

    <div class="container h-100">
        <div class="row justify-content-center">
            <div class="col-8">

                    <div class="display-3">{% block title %}evaluate{% endblock title %}</div>
                    <br>
                    <p>Here you can evaluate the quality of the predictions. Choose a project and model for which to evaluate previously executed predictions. Evaluations will be part of the file you can download under projects.</p>
                    <br>

                    <form  action="" method="post" role="form">
                        {{ form.csrf_token }}
                        {{ form.project_id.label(class_='sr-only')}}
                        {{ form.project_id(class_='custom-select') }}
                        {% if form.project_id.errors %}
                            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                                {% for error in form.project_id.errors %}
                                    <p>{{ error }}</p>
                                {% endfor %}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endif %}
                        <br><br>
                        {{ form.predictionmodel_id.label(class_='sr-only')}}
                        {{ form.predictionmodel_id(class_='custom-select') }}
                        <br><br><br>
                        <div class="row justify-content-center">
                            {{ form.submit(class_='btn btn-outline-secondary') }}
                        </div>
                    </form>
                <br>
            </div>


        </div>
    </div>



{% endblock content %}

{% block script %}
{% endblock script %}

app/frontend/vesseg/templates/main/evaluation.html
{% extends 'base.html' %}

{% block title %}evaluation{% endblock title %}

{% block content %}

    {% include 'navigation.html' %}


    <div class="container-fluid h-100">
        <br>
        <div class="row justify-content-center">
            <p>Evaluating predictions for images in project <strong>{{ project_name }}</strong> predicted with <strong>{{ predictionmodel_name }}</strong>.</p>
        </div>
        <div class="row justify-content-center">
            <p>Input image shown on left, prediction on right. Blue overlay signifies plaque, yellow signifies lumen, and purple signifies background.</p>
        </div>
        <div class="row justify-content-center">
            <p id="rating-counter"></p>
        </div>
        <br>
        <div class="row justify-content-center align-items-center">
            <button id="prev" class="btn btn-outline-secondary mx-3">Prev</button>
            <img src="" alt="" id="plain-img" class="mx-3"/>
            <img src="" alt="" id="overlay-img" class="mx-3"/>
            <button id="next" class="btn btn-outline-secondary mx-3">Next</button>
        </div>
        <br>
        <div class="row justify-content-center">
            <button class="rater-button btn btn-outline-secondary mx-5">1</button>
            <button class="rater-button btn btn-outline-secondary mx-5">2</button>
            <button class="rater-button btn btn-outline-secondary mx-5">3</button>
            <button class="rater-button btn btn-outline-secondary mx-5">4</button>
            <button class="rater-button btn btn-outline-secondary mx-5">5</button>
        </div>
        <br>
        <div class="row justify-content-center">
                <p>Rate prediction from 1 (poor) to 5 (excellent).</p>
        </div>
        <div class="row justify-content-center">
                <p>Current rating:</p><p id="current-rating"></p>
        </div>
    </div>



{% endblock content %}

{% block script %}
    <script>

        let evaluation = {{ evaluation | tojson }};
        let current_evaluation = 0;
        let csrf_token = "{{ csrf_token() }}";

        loadImage = function(i){
            if (current_evaluation == evaluation.length - 1 && i == 1) {
                alert('This is the last prediction.');
            } else if (current_evaluation == 0 && i == -1) {
                alert('This is the first prediction.');
            } else {
                current_evaluation += i;
                $('#plain-img').attr('src', '/data/image' + evaluation[current_evaluation]['image_path'])
                $('#overlay-img').attr('src', '/data/image' + evaluation[current_evaluation]['mask_path'])
                $('#rating-counter').text(String(current_evaluation + 1) + '/' + String(evaluation.length));
                $('#current-rating').text(evaluation[current_evaluation]['current_evaluation'])
            };
        };

        loadImage(0);


        $('#next').click(function () {loadImage(1)});
        $('#prev').click(function () {loadImage(-1)});

        $('.rater-button').click(function () {

            $.ajax({
                beforeSend: function(xhr, settings) {
                    if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
                        xhr.setRequestHeader("X-CSRFToken", csrf_token);
                    }
                },
                type: "POST",
                url: '/data/evaluation',
                data: {mask_id: evaluation[current_evaluation]['mask_id'], new_evaluation: $(this).text()},
                success: function (data) {
                    evaluation[current_evaluation]['current_evaluation'] = $.parseJSON(data)['evaluation'];
                    $('#current-rating').text(evaluation[current_evaluation]['current_evaluation'])
                    loadImage(1);
                }
            })
        });


    </script>
{% endblock script %}

app/frontend/vesseg/templates/main/home.html
{% extends 'main/base.html' %}
{% block title %}home{% endblock title %}
{% block maincontent %}

    <br>
    <div class="display-1">welcome</div>
    <br>

    <div class="row">
    This is vesseg, a tool to speed up atherosclerosis research. It is being developed by the Computational Radiology Group at the German Cancer Research Center (DKFZ) in Heidelberg, Germany, in collaboration with the Research Group for Perioperative Vascular Biology at the Clinic for Anaesthesiology at the University Hospital Heidelberg and the Institute for Artificial Intelligence in Medicine (IKIM) at the University Hospital Essen.
    </div>

    <br>
    <div class="row">
    Please direct questions and feedback at jacobmatthewmurray at gmail dot com.
    </div>

{% endblock maincontent %}

app/frontend/vesseg/templates/main/predict.html
{% extends 'main/base.html' %}

{% block maincontent %}


    <div class="display-3">{% block title %}predict{% endblock title %}</div>
    <br>
    <p>This is the core of vesseg. Choose project with <strong>previously uploaded images</strong>. Then choose model to use. More models will be added over time. Hit 'predict'. This process will automatically determine necessary steps and execute in the background. Go to Tasks, to check on progress.</p>
    <p>The current models are based on the following two U-Net-based segmentation pipelines:</p>
    <pre class="bg-light"><code>Fabian Isensee, Paul F. Jäger, Simon A. A. Kohl, Jens Petersen, Klaus H. Maier-Hein "Automated Design of Deep Learning Methods for Biomedical Image Segmentation" arXiv preprint arXiv:1904.08128 (2020).</code></pre>
    <pre class="bg-light"><code>Howard, Jeremy, and Sylvain Gugger. “Fastai: A Layered API for Deep Learning.” Information 11.2 (2020): 108. Crossref. Web.</code></pre>

    <form  action="" method="post" role="form">
        {{ form.csrf_token }}
        {{ form.project_id.label(class_='sr-only')}}
        {{ form.project_id(class_='custom-select') }}
        {% if form.project_id.errors %}
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                {% for error in form.project_id.errors %}
                    <p>{{ error }}</p>
                {% endfor %}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endif %}
        <br><br>
        {{ form.predictionmodel_id.label(class_='sr-only')}}
        {{ form.predictionmodel_id(class_='custom-select') }}
        <br><br><br>
        <div class="row justify-content-center">
            {{ form.submit(class_='btn btn-outline-secondary') }}
        </div>
    </form>

    <br><br><br>

    {% with messages = get_flashed_messages(category_filter=['predict']) %}
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    {{ message }}
                    {% if tasks %}
                    <br><br>
                    <p>Progress:</p>
                    {% for task in tasks %}
                        <div class="progress">
                          <div class="progress-bar" id="{{ task.task_id }}" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%">
                            <span class="sr-only"></span>
                          </div>
                        </div>
                        <br>
                    {% endfor %}
                    {% endif %}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}

{% endblock maincontent %}
{% block script %}
    <script>
        {% if tasks %}

            let tasks = [];
            let progress = [];
            {% for t in tasks %}
                tasks.push('{{ t.task_id }}');
                progress.push(0);
            {% endfor %}
            const arrSum = arr => arr.reduce((a,b) => a + b, 0);
            let tid = setInterval(updateStatus, 2000);

            function abortTimer() {
                clearInterval(tid);
            };

            function updateStatus(){
                for (i=0; i<tasks.length; i++) {
                    $.get('/tasks/status', {task_id: tasks[i]}, function(data){
                        let my_progress = $.parseJSON(data)['progress'];
                        let task_id = $.parseJSON(data)['task_id'];
                        document.getElementById(task_id).setAttribute('aria_valuenow', my_progress);
                        document.getElementById(task_id).style.width =  my_progress +'%';
                    });
                    progress[i] = parseInt(document.getElementById(tasks[i]).getAttribute('aria_valuenow'));
                }
                if (arrSum(progress) == tasks.length*100) {
                    abortTimer()
                }
            }

        {% endif %}
    </script>
{% endblock script %}

app/frontend/vesseg/templates/main/project.html
{% extends 'main/base.html' %}

{% block maincontent %}


    <div class="display-3">{% block title %}project{% endblock title %}</div>
    <br>
    <p>Enter a project name and click 'create' to begin a new project. Hit 'delete' in project list to delete project, <strong>including all uploaded data</strong>.</p>
    <br>

    <form  action="" method="post" role="form">
        {{ form.csrf_token }}
        <div class="form-row">
            <div class="col flex-grow-1">
                {{ form.project.label(class_='sr-only')}}
                {{ form.project(class_='form-control', placeholder='project name') }}
            </div>
            {{ form.submit(class_="btn btn-outline-secondary")}}
        </div>
    </form>
    <br>

    {% if form.project.errors %}
        {% for error in form.project.errors %}
            <div class="alert alert-danger" role="alert">
                {{ error }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endfor %}
    {% endif %}


    <br><br>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">project</th>
                <th scope="col">created</th>
                <th scope="col">download</th>
                <th scope="col">delete</th>
            </tr>
        </thead>
        <tbody>
        {% for p in projects %}
            <tr>
                <th scope="row"> {{ loop.index }}</th>
                <td>{{ p.project }}</td>
                <td>{{ p.created_on.strftime('%Y-%m-%d') }}</td>
                <td><a href="{{ url_for('main.download_project', project_id=p.id) }}">download</a></td>
                <td><a href="{{ url_for('main.project_delete', project_id=p.id) }}">delete</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock maincontent %}

{% block script %}
{% endblock script %}